version: '3.8'

services:
  odoo:
    image: odoo:latest
    container_name: odoo
    hostname: odoo
    restart: always
    ports:
      - "${ODOO_PORT}:8069"
    # environment:
    #   - HOST=${DB_HOST}
    #   - USER=${DB_USER}
    #   - PASSWORD=${DB_PASSWORD}
    # command: odoo -i base
    volumes:
      - ./odoo_data/odoo-web-data:/var/lib/odoo
      - ./odoo_data/addons:/mnt/extra-addons
      - ./odoo_data/config/:/etc/odoo/
    networks:
      - odoo-network
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-odoo
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - odoo-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-odoo
    hostname: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "${PG_ADMIN_PORT}:80"
    networks:
      - odoo-network

networks:
  odoo-network:
      external: true
